# Generated by Django 4.2.4 on 2023-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=1234567890),
            preserve_default=False,
        ),
    ]
